--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchased_amount) as revenue
from customer 
group by gender; 

-- changing table name 
alter table customer
rename purcahsed_amount to purchased_amount;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchased_amount 
from customer 
where discount_applied = 'Yes' and purchased_amount >=(select avg(purchased_amount) from customer) 

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average_Product_Rating"  from customer
group by item_purchased order by avg(review_rating) desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type , round(avg(purchased_amount),2) from customer 
where shipping_type in ('Express','Standard') group by 1 

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status ,count(customer_id) as Total_Customer, round(sum(purchased_amount),2) as Total_revenue, round(avg(purchased_amount),2) as average_spend from customer
group by subscription_status
order by 3 , 4 desc ;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate from customer 
group by item_purchased order by discount_rate desc limit 5; 
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--    and show the count of each segment
with customer_type as 
(select customer_id,previous_purchases, case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning' else 'Loyal' end as customer_segment from customer)

select customer_segment,count(*)  as "number of customers" from customer_type group by 1  
--Q8. What are the top 3 most purchased products within each category?
with item_count as 
(select category,item_purchased,
count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as item_rank from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders from item_count where item_rank <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as Repeat_buyers from customer
where previous_purchases >= 5 group by 1 


--Q10. What is the revenue contribution of each age group?

select age_group , sum(purchased_amount) as total_revenue from customer group by 1 order by 2 desc